import type { NextPage } from 'next'
import Head from "next/head";
import Image from "next/image";
import styles from '../styles/Home.module.css'
import { useState } from "react";
import { initializeApp, getApps } from 'firebase/app';
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";

const Login: NextPage = () => {
    
   const apps = getApps()
   if (apps.length === 0) {
        initializeApp({
            // TODO 管理方法考える
        })
    } else {
        console.log(apps)
    }

    const [query, setQuery] = useState({
        email: "",
        password: "",
    });

    // Update inputs value
    const handleParam = () => (e: any) => { // TODO any?
        const name = e.target.name;
        const value = e.target.value;
        setQuery((prevState) => ({
        ...prevState,
        [name]: value,
        }));
    };


    const login = (email: string, password: string) => {
        const auth = getAuth()
        createUserWithEmailAndPassword(auth, email, password)
            .then((userCredential) => {
                console.log(JSON.stringify(userCredential));
            })
            .catch((error) => {
                console.error(JSON.stringify(error));
            });
    };

    const formSubmit = () => {
        login(query.email, query.password);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <form>
                    <label>
                        <input
                        name="email"
                        type="email"
                        placeholder="email"
                        value={query.email}
                        onChange={handleParam()}
                        />
                    </label>
                    <label>
                        <input
                        name="password"
                        type="password"
                        placeholder="password"
                        value={query.password}
                        onChange={handleParam()}
                        />
                    </label>
                </form>
                <button onClick={formSubmit}>Login</button>
            </main>

            <footer className={styles.footer}>
                <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Powered by{" "}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
                </a>
            </footer>
        </div>
    )
}

export default Login